If the clocked schedule is tied to a one off task, don't disable it. …
celery/django-celery-beat pull request #350
Opened 2020-06-13 20:36 UTC by vbabiy

As far as I can tell there is no reason to disable the clock, sine that the task will get disabled on the next run.

2020-06-13 20:36 UTC, vbabiy commented
This should fix #150

2020-06-29 03:36 UTC, yywing commented
I dont think so. I update my pr.

2021-01-18 16:31 UTC, auvipy commented
> I dont think so. I update my pr.

which PR, please?

2021-09-11 17:11 UTC, auvipy requested changes
rebase please

2021-12-11 10:36 UTC, auvipy commented
this change is not relevant anymore

2021-12-11 10:36 UTC, closed without merging