Add Korean translation
celery/django-celery-beat pull request #504
Opened 2022-01-24 12:43 UTC by Kirade

I added Korean translations.
I hope this translation would help developers who speaks Korean

Thanks!

2022-01-24 12:47 UTC, auvipy requested changes
need some more korean speakers to review this :)

2022-01-25 02:23 UTC, leehosung commented on django_celery_beat/locale/ko/LC_MESSAGES/django.po
> +msgstr "선택된 테스크들을 작동시킵니다."
how about this?
```suggestion
msgstr "선택된 테스크들을 실행 합니다."
```

2022-01-25 02:29 UTC, twins1040 reviewed
테스크 보다 태스크 라고 많이 쓰는 것 같습니다.

2022-01-25 02:29 UTC, twins1040 commented on django_celery_beat/locale/ko/LC_MESSAGES/django.po
> +msgstr "천문 박명"
dawn 은 새벽 아닌가요?

2022-01-25 02:29 UTC, twins1040 commented on django_celery_beat/locale/ko/LC_MESSAGES/django.po
> +msgstr "테스크의 간단한 설명을 작성합니다."
`태스크에 대한 간단한 설명` 과 같이 명사형이어야 하지 않을지?

2022-01-25 02:29 UTC, twins1040 commented on django_celery_beat/locale/ko/LC_MESSAGES/django.po
> +msgstr "천문 박명"
박명이 혹시 새벽이라는 뜻이면 그냥 새벽이 나을듯

2022-01-25 02:37 UTC, Kirade commented on django_celery_beat/locale/ko/LC_MESSAGES/django.po
> +msgstr "천문 박명"
https://ko.wikipedia.org/wiki/%EB%B0%95%EB%AA%85

공식 명칭을 따르는게 좋아보여요.

2022-01-25 02:37 UTC, leehosung reviewed
I could'n find a good Korean word for "solar event".

2022-01-25 02:37 UTC, leehosung commented on django_celery_beat/locale/ko/LC_MESSAGES/django.po
> +msgstr "Periodic Tasks"
```suggestion
msgstr "주기적인 테스크들"
```

2022-01-25 02:40 UTC, Kirade commented on django_celery_beat/locale/ko/LC_MESSAGES/django.po
> +msgstr "테스크의 간단한 설명을 작성합니다."
beat 특성상 어드민에서 대부분 보여지게 되는데요.
어드민을 사용하는 쪽에서 읽기 쉽게 작성한것이 의도였습니다.

2022-01-25 02:41 UTC, Kirade commented
> 테스크 보다 태스크 라고 많이 쓰는 것 같습니다.

넵 태스크로 바꿔볼께요.

2022-01-25 02:48 UTC, Kirade commented on django_celery_beat/locale/ko/LC_MESSAGES/django.po
> +msgstr "천문 박명"
https://ko.wikipedia.org/wiki/%EB%B0%95%EB%AA%85

공식 명칭을 따랐습니다.

2022-01-25 02:52 UTC, Kirade commented on django_celery_beat/locale/ko/LC_MESSAGES/django.po
> +msgstr "Periodic Tasks"
Thanks

<img width="619" alt="Screen Shot 2022-01-25 at 11 49 48 AM" src="https://user-images.githubusercontent.com/13049936/150902158-aae73b75-06d1-445b-b454-4db53ae1946d.png">

2022-01-25 02:56 UTC, Kirade commented
Changes Applied!

@leehosung @twins1040

2022-01-25 04:56 UTC, auvipy requested changes
can yo just pull changes from master?

2022-01-25 05:14 UTC, Kirade commented
Sure. :)

2022-01-25 05:41 UTC, auvipy approved these changes

2022-01-25 05:41 UTC, merged

2022-06-25 13:06 UTC, bakyeono commented on django_celery_beat/locale/ko/LC_MESSAGES/django.po
> +msgstr "가,들이"
This looks mistyped.

2022-06-26 10:44 UTC, auvipy commented on django_celery_beat/locale/ko/LC_MESSAGES/django.po
> +msgstr "가,들이"
contributions are welcome