deps: support django 4.1
celery/django-celery-beat pull request #581
Opened 2022-09-19 16:50 UTC by csrftoken

2022-09-20 07:49 UTC, benedikt-bartscher commented
https://github.com/celery/django-celery-beat/pull/567

2022-09-30 17:37 UTC, evanlesmez commented
How is this going?

2022-10-12 10:57 UTC, auvipy requested changes

2022-10-12 10:57 UTC, auvipy commented on requirements/docs.txt
> +Django>=2.2,<=4.1
```suggestion
Django>=2.2,<4.2
```

2022-10-12 10:58 UTC, auvipy requested changes

2022-10-12 10:58 UTC, auvipy commented on requirements/runtime.txt
> +Django>=2.2,<=4.1
```suggestion
Django>=2.2,<4.2
```

2022-10-12 10:59 UTC, auvipy requested changes

2022-10-12 10:59 UTC, auvipy commented on requirements/test-django.txt
> +Django>=3.2,<=4.1
```suggestion
Django>=3.2,<4.2
```

2022-10-12 13:35 UTC, auvipy commented
not sure why py3.7 is failing

2022-10-12 18:25 UTC, goatwu1993 commented
@auvipy Upstream error by kombu & celery, caused by using importlib-metadata API which is deprecated at 5.0.0

Both libs have been fixed and merged but in 5.3.0 milestone.

https://github.com/celery/kombu/pull/1601
https://github.com/celery/celery/pull/7785

Only python < 3.8 needs importlib-metadata, which is why only python37 breaks here.

2022-10-13 08:11 UTC, goatwu1993 commented
rebase should pass 3.7

2022-10-13 08:15 UTC, merged