optimize: avoid initializing schedules.crontab
celery/django-celery-beat pull request #687
Opened 2023-10-13 08:33 UTC by k8scat

2023-10-14 05:21 UTC, auvipy requested changes
I have started the CI. is it possible to adjust/add some test for the change

2023-10-17 02:18 UTC, k8scat commented
> I have started the CI. is it possible to adjust/add some test for the change

how can I add a test for `CrontabSchedule` model in this case

2023-10-17 02:34 UTC, k8scat commented
> I have started the CI. is it possible to adjust/add some test for the change

test added

2023-11-03 02:08 UTC, k8scat commented
> I have started the CI. is it possible to adjust/add some test for the change

😸

2023-11-08 14:38 UTC, auvipy requested changes
I would like to know more context about the change. why it is useful and if it breaks current apps

2023-11-15 01:13 UTC, closed without merging

2023-11-15 04:49 UTC, auvipy commented
reason for closing please?

2023-11-15 05:58 UTC, k8scat commented
> reason for closing please?

maybe not necessary

2023-11-15 06:09 UTC, auvipy commented
may I know why you feel that?