Upgrade GitHub Actions and PyPy
celery/django-celery-beat pull request #699
Opened 2023-12-06 21:53 UTC by cclauss

2023-12-09 08:59 UTC, cclauss commented
@auvipy Can you please approve the workflow runs so I can see if these tests pass?

2023-12-12 15:57 UTC, Koff commented
Could we get a status update on this? I want to upgrade to Django 5, but I can't because of the incompatibility with `django-celery-beat` latest.

2023-12-13 13:21 UTC, ddoroshev commented
![image](https://github.com/celery/django-celery-beat/assets/114997037/234118ba-466e-4764-b45a-521eb5a0dcf0)

2023-12-13 19:31 UTC, auvipy commented on tox.ini
> +    pip install --upgrade https://github.com/celery/celery/zipball/master#egg=celery
```suggestion
    pip install --upgrade https://github.com/celery/celery/zipball/main#egg=celery
```

2023-12-13 19:31 UTC, auvipy commented on tox.ini
> +    pip install --upgrade https://github.com/celery/kombu/zipball/master#egg=kombu
```suggestion
    pip install --upgrade https://github.com/celery/kombu/zipball/main#egg=kombu
```

2023-12-19 19:23 UTC, auvipy requested changes
can you please check the pypy failure?

2023-12-19 21:05 UTC, auvipy approved these changes
good decision and great job

2023-12-19 21:05 UTC, merged