added sphinxcontrib-django to extensions
celery/django-celery-beat pull request #736
Opened 2024-02-20 23:02 UTC by mfosterw

Closes #735. To test this, first install the new dependency with `pip install requirements/docs.txt` and then build the docs normally.

2024-02-20 23:04 UTC, mfosterw commented on requirements/docs.txt
> +sphinxcontrib-django
We can pin this to a specific version if necessary but I don't really see the need

2024-02-20 23:14 UTC, mfosterw commented on docs/reference/django-celery-beat.models.rst
> -    :undoc-members:
This directive causes the fields documented by the extension to be listed twice

2024-02-25 16:29 UTC, cclauss commented
The only problem that I see is that this dependency [does not yet support Django v5](https://github.com/sphinx-doc/sphinxcontrib-django/blob/f4dfbbd382e6bb244d0f9ac7ee0b8930cff64c5e/pyproject.toml#L13-L15) and we want to put out a release that does support Dj5.  Could you please check to see if that will present problems?

2024-02-26 20:20 UTC, mfosterw commented
Setting the minimum version of Django to 5.0 did not cause any problems installing or running this for me, and since it's only a docs dependency I assume it shouldn't affect users directly.

2024-02-26 21:45 UTC, cclauss requested changes
Blocked by sphinx-doc/sphinxcontrib-django#66

2024-02-28 23:00 UTC, 50-Course commented
Thank you for this patch @mfosterw, while the former patch to this, does look informative enough, the latter shows great ease of use for developers. 

That said we can only push for https://github.com/sphinx-doc/sphinxcontrib-django/pull/66 to get merged.

Once again thank you @cclauss, @mfosterw.

Good job!

2024-03-03 15:40 UTC, cclauss approved these changes

2024-03-03 16:01 UTC, Nusnus approved these changes
Very nice, thank you!

2024-03-03 16:01 UTC, merged