Fix for missing periodic task name in results
celery/django-celery-beat pull request #812
Opened 2024-10-08 13:33 UTC by ntindicator

Fix for issue [#376](https://github.com/celery/django-celery-results/issues/376) in [django-celery-results](https://github.com/celery/django-celery-results/). The message broker rabbitmq isn't picking up `periodic_task_name` when it's passed as a keyword arg to `task.apply_async()`. If it's added to the `headers` in `apply_async()` it becomes available in the `request` object in django-celery-results. For this change to work the following [commit](https://github.com/celery/django-celery-results/commit/8ea61e19689864fbebb81f3552bf669a7150e325) also needs to be merged, otherwise it won't get picked up in the results. 

If the task isn't triggered by django-celery-beat, but is done with code, such as using `delay()` or `apply_async()`, it will be missing, unless it's added to the headers in [`apply_async()`](https://docs.celeryq.dev/en/stable/reference/celery.app.task.html#celery.app.task.Task.apply_async). [delay()](https://docs.celeryq.dev/en/stable/reference/celery.app.task.html#celery.app.task.Task.delay) doesn't support the extra options. E.g. When triggering a child task with `delay()` Periodic Task Name was missing in the Task Results.

These changes haven't been tested with Redis or any other message broker, only rabbitmq. `CELERY_RESULT_EXTENDED` was set to `True` in the settings.

Tested with: 
celery==5.4.0 
django-celery-beat==2.7.0 
django-celery-results==2.5.1
Django==4.2.16
rabbitmq==4.0.2

2024-10-08 14:15 UTC, Nusnus submitted a review, later dismissed
Is it possible to add unit tests please?

2024-10-14 14:59 UTC, cclauss commented
Linting errors in `pre-commit`:
```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

django_celery_beat/admin.py:252:9: E303 too many blank lines (2)
django_celery_beat/admin.py:254:59: E231 missing whitespace after ':'
django_celery_beat/admin.py:257:30: E128 continuation line under-indented for visual indent
django_celery_beat/admin.py:257:59: E231 missing whitespace after ':'
t/unit/test_schedulers.py:874:5: E303 too many blank lines (2)
t/unit/test_schedulers.py:879:80: E501 line too long (81 > 79 characters)
```

2024-10-21 11:49 UTC, auvipy requested changes
depends on https://github.com/celery/django-celery-results/pull/445#pullrequestreview-2381806705

2024-10-23 11:50 UTC, auvipy approved these changes

2024-12-14 09:46 UTC, auvipy requested changes
can you please rebase?

2025-01-12 07:29 UTC, auvipy approved these changes

2025-01-12 07:36 UTC, merged

2025-01-12 07:37 UTC, auvipy commented
Thanks for your efforts